# Generated by Django 4.2.11 on 2025-08-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zscore", "0002_zscorehistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zscorehistory",
            name="hours",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
