# Generated by Django 4.2.11 on 2025-08-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zscore", "0003_zscorehistory_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zscorehistory",
            name="hours",
            field=models.IntegerField(),
        ),
    ]
