# Generated by Django 4.2.11 on 2025-08-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zscore", "0005_remove_zscorehistory_cs_zscore_h_symbol__9b2dd5_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="zscorehistory",
            name="cs_zscore_h_symbol__819d5d_idx",
        ),
        migrations.AddIndex(
            model_name="zscorehistory",
            index=models.Index(
                fields=["calculated_at"],
                include=("price", "volume", "trades", "hours", "symbol_id"),
                name="idx_zscore_calculated_covering",
            ),
        ),
    ]
