# Generated by Django 4.2.11 on 2025-10-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zscore', '0006_remove_zscorehistory_cs_zscore_h_symbol__819d5d_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZScoreHistorical',
        ),
    ]
