# Generated by Django 4.2.11 on 2025-04-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementalCorrelationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf', models.IntegerField(db_index=True)),
                ('data_type', models.CharField(db_index=True, max_length=50)),
                ('symbol_a', models.CharField(db_index=True, max_length=50)),
                ('symbol_b', models.CharField(db_index=True, max_length=50)),
                ('window_size', models.IntegerField()),
                ('x_values', models.BinaryField()),
                ('y_values', models.BinaryField()),
                ('sum_x', models.FloatField()),
                ('sum_y', models.FloatField()),
                ('sum_xx', models.FloatField()),
                ('sum_yy', models.FloatField()),
                ('sum_xy', models.FloatField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'cs_correlations_state',
                'ordering': ['-tf', 'data_type', 'symbol_a', 'symbol_b'],
                'unique_together': {('tf', 'data_type', 'symbol_a', 'symbol_b')},
            },
        ),
    ]
