# Generated by Django 4.2.11 on 2025-04-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf', models.IntegerField()),
                ('data_type', models.CharField(max_length=50)),
                ('symbol_a', models.CharField(max_length=50)),
                ('symbol_b', models.CharField(max_length=50)),
                ('correlation_value', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['tf', 'data_type', 'symbol_a', 'symbol_b'], name='correlation_tf_18a7ae_idx')],
                'unique_together': {('tf', 'data_type', 'symbol_a', 'symbol_b')},
            },
        ),
    ]
