# Generated by Django 4.2.11 on 2025-10-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0002_correlationpairhistory_delete_correlationhistory_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='correlationpairhistory',
            table='cs_correlation_pair_history',
        ),
    ]
