# Generated by Django 4.2.11 on 2025-06-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0002_correlation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correlation',
        ),
        migrations.DeleteModel(
            name='IncrementalCorrelationState',
        ),
    ]
