# Generated by Django 4.2.11 on 2025-10-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0003_alter_correlationpairhistory_table'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='correlationpairhistory',
            name='unique_correlation_entry',
        ),
    ]
