# Generated by Django 4.2.11 on 2025-10-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0004_remove_correlationpairhistory_unique_correlation_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlationpairhistory',
            name='calculated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this correlation was calculated'),
        ),
        migrations.AlterField(
            model_name='correlationpairhistory',
            name='data_type',
            field=models.CharField(help_text="Type of data used for correlation (e.g., 'close', 'volume', 'trades')", max_length=20),
        ),
        migrations.AlterField(
            model_name='correlationpairhistory',
            name='hours',
            field=models.IntegerField(help_text='Time window in hours used for correlation calculation'),
        ),
        migrations.AddIndex(
            model_name='correlationpairhistory',
            index=models.Index(fields=['data_type', 'hours', '-calculated_at'], name='cs_correlat_data_ty_11981e_idx'),
        ),
    ]
