# Generated by Django 4.2.11 on 2025-10-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0005_alter_correlationpairhistory_calculated_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='correlationpairhistory',
            index=models.Index(fields=['calculated_at'], name='cs_correlat_calcula_4f6504_idx'),
        ),
    ]
