# Generated by Django 5.2 on 2025-12-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0010_partition_correlation_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correlationpairhistory',
            options={'managed': False, 'ordering': ['-calculated_at']},
        ),
    ]
