# Generated by Django 4.2.11 on 2025-04-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('color', models.CharField(default='#000000', max_length=20)),
            ],
            options={
                'db_table': 'crypto_scanner_binance_spot_tickers',
            },
        ),
        migrations.CreateModel(
            name='BinanceSpotKline5m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=10, max_digits=24)),
                ('close', models.DecimalField(decimal_places=10, max_digits=24)),
                ('high', models.DecimalField(decimal_places=10, max_digits=24)),
                ('low', models.DecimalField(decimal_places=10, max_digits=24)),
                ('base_volume', models.DecimalField(decimal_places=10, max_digits=24)),
                ('number_of_trades', models.IntegerField()),
                ('quote_asset_volume', models.DecimalField(decimal_places=10, max_digits=24)),
                ('taker_buy_base_asset_volume', models.DecimalField(decimal_places=10, max_digits=24)),
                ('taker_buy_quote_asset_volume', models.DecimalField(decimal_places=10, max_digits=24)),
                ('ticker_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exchange_connections.ticker')),
                ('ticker_quote', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quote_ticker', to='exchange_connections.ticker')),
            ],
            options={
                'db_table': 'crypto_scanner_binance_spot_kline_5m',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['ticker', '-end_time'], name='crypto_scan_ticker_3699c7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='binancespotkline5m',
            constraint=models.UniqueConstraint(fields=('ticker', 'start_time'), name='unique_ticker_start_time'),
        ),
    ]
