# Generated by Django 4.2.11 on 2025-04-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kline1m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('close_time', models.DateTimeField()),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('open', models.DecimalField(decimal_places=8, max_digits=18)),
                ('close', models.DecimalField(decimal_places=8, max_digits=18)),
                ('high', models.DecimalField(decimal_places=8, max_digits=18)),
                ('low', models.DecimalField(decimal_places=8, max_digits=18)),
                ('base_volume', models.DecimalField(decimal_places=8, max_digits=24)),
                ('quote_volume', models.DecimalField(decimal_places=8, max_digits=24)),
                ('taker_buy_base_volume', models.DecimalField(decimal_places=8, max_digits=24)),
                ('taker_buy_quote_volume', models.DecimalField(decimal_places=8, max_digits=24)),
                ('number_of_trades', models.IntegerField()),
                ('exchange', models.CharField(db_index=True, max_length=20)),
                ('contract_type', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'db_table': 'cs_klines_1m',
                'ordering': ['-start_time', 'symbol'],
                'indexes': [models.Index(fields=['symbol', 'exchange', '-start_time', 'contract_type'], name='klines_main_query_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='kline1m',
            constraint=models.UniqueConstraint(fields=('start_time', 'symbol', 'exchange', 'contract_type'), name='unique_klines_1m_fields'),
        ),
    ]
