# Generated by Django 4.2.11 on 2025-10-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zscore', '0007_delete_zscorehistorical'),
        ('exchange_connections', '0002_remove_kline1m_klines_main_query_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BinanceSpotKline5m',
        ),
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
