# Generated by Django 4.2.11 on 2025-08-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_connections', '0003_contracttype_exchange_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kline1m',
            name='unique_klines_1m_fields',
        ),
        migrations.RemoveIndex(
            model_name='kline1m',
            name='klines_main_query_idx',
        ),
        migrations.RemoveField(
            model_name='kline1m',
            name='contract_type',
        ),
        migrations.AddField(
            model_name='symbol',
            name='contract_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange_connections.contracttype'),
        ),
        migrations.AddIndex(
            model_name='kline1m',
            index=models.Index(fields=['symbol', 'exchange', '-start_time'], name='klines_main_query_idx'),
        ),
        migrations.AddConstraint(
            model_name='kline1m',
            constraint=models.UniqueConstraint(fields=('start_time', 'symbol', 'exchange'), name='unique_klines_1m_fields'),
        ),
        migrations.AddConstraint(
            model_name='symbol',
            constraint=models.UniqueConstraint(fields=('name', 'exchange', 'contract_type'), name='unique_symbol_fields'),
        ),
    ]
