# Generated by Django 4.2.2 on 2023-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_scanner', '0002_snippet_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtcPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
