# Generated by Django 4.2.2 on 2023-07-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_scanner', '0003_btcprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='binance_btc_kline_1m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=10, max_digits=20)),
                ('close', models.DecimalField(decimal_places=10, max_digits=20)),
                ('high', models.DecimalField(decimal_places=10, max_digits=20)),
                ('low', models.DecimalField(decimal_places=10, max_digits=20)),
                ('base_volume', models.DecimalField(decimal_places=10, max_digits=20)),
                ('number_of_trades', models.IntegerField()),
                ('quote_asset_volume', models.DecimalField(decimal_places=10, max_digits=20)),
                ('taker_buy_base_asset_volume', models.DecimalField(decimal_places=10, max_digits=20)),
                ('taker_buy_quote_asset_volume', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
