# Generated by Django 4.2.2 on 2023-07-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_scanner', '0006_binance_adausdt_kline_1m_binance_avaxusdt_kline_1m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binance_adausdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_adausdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_adausdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_adausdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_adausdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_adausdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_adausdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_adausdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_avaxusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_avaxusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_avaxusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_avaxusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_avaxusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_avaxusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_avaxusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_avaxusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bchusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bchusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bchusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bchusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bchusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bchusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bchusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bchusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bnbusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bnbusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bnbusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bnbusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bnbusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bnbusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bnbusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_bnbusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_btcusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_btcusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_btcusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_btcusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_btcusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_btcusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_btcusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_btcusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dogeusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dogeusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dogeusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dogeusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dogeusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dogeusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dogeusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dogeusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dotusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dotusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dotusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dotusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dotusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dotusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dotusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_dotusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ethusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ethusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ethusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ethusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ethusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ethusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ethusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ethusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_linkusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_linkusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_linkusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_linkusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_linkusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_linkusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_linkusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_linkusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ltcusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ltcusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ltcusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ltcusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ltcusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ltcusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ltcusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_ltcusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_maticusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_maticusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_maticusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_maticusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_maticusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_maticusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_maticusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_maticusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_shibusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_shibusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_shibusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_shibusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_shibusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_shibusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_shibusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_shibusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_solusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_solusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_solusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_solusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_solusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_solusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_solusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_solusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_uniusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_uniusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_uniusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_uniusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_uniusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_uniusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_uniusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_uniusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_xrpusdt_kline_1m',
            name='base_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_xrpusdt_kline_1m',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_xrpusdt_kline_1m',
            name='high',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_xrpusdt_kline_1m',
            name='low',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_xrpusdt_kline_1m',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_xrpusdt_kline_1m',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_xrpusdt_kline_1m',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='binance_xrpusdt_kline_1m',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
    ]
