# Generated by Django 4.2.2 on 2023-07-18 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_scanner', '0008_binancespotkline1m'),
    ]

    operations = [
        migrations.DeleteModel(
            name='binance_adausdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_avaxusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_bchusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_bnbusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_btcusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_dogeusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_dotusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_ethusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_linkusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_ltcusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_maticusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_shibusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_solusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_uniusdt_kline_1m',
        ),
        migrations.DeleteModel(
            name='binance_xrpusdt_kline_1m',
        ),
    ]
