# Generated by Django 4.2.2 on 2023-09-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_scanner', '0011_binancespotkline5m'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
