# Generated by Django 4.2.2 on 2023-10-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_scanner', '0012_delete_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceSpotTickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('color', models.CharField(default='#000000', max_length=20)),
            ],
            options={
                'db_table': 'crypto_scanner_binance_spot_tickers',
            },
        ),
    ]
